### ISSUE TITLE
IndexError: index xxx is out of bounds for axis 0 with size xxx

### ISSUE THREAD

**Issue by jpainam** [ahangchen/rank-reid#7]
Hi!
Given the market1501 dataset which training size is `12,936`. This [line](https://github.com/ahangchen/rank-reid/blob/98a30063e2594a3d5576716aefa88fcaa49be14b/baseline/evaluate.py#L81) outputs `(12936,12936)`. In the `train_predict` function, you wrote
```python
# ignore top1 because it's the origin image
np.savetxt(score_path, result[:, 1:], fmt='%.4f')
np.savetxt(pid_path, result_argsort[:, 1:], fmt='%d')
```
which basically decreased the size of array and resulted in a dimension of  `(12936,12935)`.
[This line](https://github.com/ahangchen/rank-reid/blob/98a30063e2594a3d5576716aefa88fcaa49be14b/baseline/evaluate.py#L102), will result in the error
```python
p_t_idx = result_argsort[q_index][t_index]
IndexError: index 12935 is out of bounds for axis 0 with size 12935
```
This [line](https://github.com/ahangchen/rank-reid/blob/98a30063e2594a3d5576716aefa88fcaa49be14b/baseline/evaluate.py#L101) can be changed to  `for t_index in range(len(test_info) - 1):` for `train_predict` or replace [this line](https://github.com/ahangchen/rank-reid/blob/98a30063e2594a3d5576716aefa88fcaa49be14b/baseline/evaluate.py#L102) with
```python
try:
    p_t_idx = result_argsort[q_index][t_index]
except IndexError:
    continue
``` 
Any comment is welcomed and I can submit a PR request if you need

**Comment by ahangchen** [comment]
We decrease the size to 12935 because we ignore the visual similarity of one training image with itself, which is not useful in our following transfering experiments. 

[map_rank_quick_eval](https://github.com/ahangchen/rank-reid/blob/98a30063e2594a3d5576716aefa88fcaa49be14b/baseline/evaluate.py#L92) is design to evaluate on test set. We won't use it to evaluate on Market training set, which is very different from test set. But you can add a try-catch as you wrote if you would.

What matters is, if we modify this [line](https://github.com/ahangchen/rank-reid/blob/98a30063e2594a3d5576716aefa88fcaa49be14b/baseline/evaluate.py#L101), by changing it to `for t_index in range(len(test_info) - 1)`, it will produce wrong answers on test set.
